steps:
#step 1
- name: 'maven:3-jdk-11'
  args: [ 'package' ]
#step 2
- name: 'gcr.io/cloud-builders/docker'
  args: [
   'build',
   '-t',
   'docker.io/darya2019/currencies:latest',
   '.'
  ]
#step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'release/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'